# Localhost

cache:
  enabled: false
  gzip: false

twig:
  cache: false
  debug: true

assets:
  css_pipeline: false
  css_minify: false
  js_pipeline: false
  js_minify: false

errors:
  display: true
  verbosity: 2 # Full stack trace

debugger:
  enabled: true
  twig: true
  shutdown:
    close_connection: false

images:
  default_image_quality: 90
  cache_all: false

piwik:
  enabled: false

google_analytics:
  enabled: false